import smalllogo from './assets/smalllogo.png';
import biglogo from './assets/biglogo.png';
import medlogo from './assets/medlogo.png';
import medlogo2 from './assets/medlogo2.png';
import hero from './assets/hero.png';
import herobg from './assets/herobg.png';
import syngas from './assets/syngas.png';
import charcoal from './assets/charcoal.jpg';
import biooil from './assets/biooil.png';
import profile from './assets/profile.png';
import pyrogas from './assets/PYROGAS.gif';
import aboutimg from './assets/aboutimg.png';
import power from './assets/power.png';
import domestic from './assets/domestic.png';
import transport from './assets/transport.png';
import Picture45 from './assets/Picture45.png';
import Picture46 from './assets/Picture46.png';
import Picture44 from './assets/Picture44.png';
import Picture48 from './assets/Picture48.png';
import Picture47 from './assets/Picture47.jpg';

export { smalllogo, biglogo, medlogo, medlogo2, hero, herobg, syngas, charcoal, biooil, profile, pyrogas, aboutimg, power, transport, domestic, Picture45, Picture46, Picture44, Picture48, Picture47 };